services:
  line_bot:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      redis:
        condition: service_healthy  # Wait until Redis passes the health check
    networks:
      - linebot_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - linebot_network

networks:
  linebot_network:
    driver: bridge